# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35825f4c68887b7e68cf1189b677312b35ffbdf8040b69bf55b889f37f70b426f2c8fc789ae7e7e5e581302f94a7765076a693f25b78cbafa44a6988572f9f4a

test:
  secret_key_base: a91a7f5111444229cfdd578e4d446c8c12eeeef8bb5921a289c48294217cd0536185f749dece739bc9dbe371c6d4511d86f02bf4065f2af36f9153ab5d6b9484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
